[2020-04-29T09:10:58.783] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-29T09:35:53.725] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-29T13:54:10.192] [ERROR] app - Request without token
[2020-04-29T13:54:10.194] [ERROR] app - 没有访问权限
[2020-04-29T13:54:13.001] [ERROR] app - Request without token
[2020-04-29T13:54:13.002] [ERROR] app - 没有访问权限
[2020-04-29T14:23:27.789] [ERROR] app - TypeError: files.map is not a function
    at Object.Post (D:\able_project\CloudServer\restful\v0\files.js:40:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-04-29T14:23:29.397] [ERROR] app - { Error: ER_DUP_ENTRY: Duplicate entry '' for key 'PRIMARY'
    at Query.Sequence._packetToError (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:200:25)
    at D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:152:18
From previous event:
    at Client_MySQL._query (D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:146:12)
    at Client_MySQL.query (D:\able_project\CloudServer\node_modules\knex\lib\client.js:197:17)
    at Runner.<anonymous> (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:146:36)
From previous event:
    at D:\able_project\CloudServer\node_modules\knex\lib\runner.js:65:21
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
From previous event:
    at Runner.run (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:51:31)
    at Builder.Target.then (D:\able_project\CloudServer\node_modules\knex\lib\interface.js:35:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlMessage: 'Duplicate entry \'\' for key \'PRIMARY\'',
  sqlState: '23000',
  index: 0,
  sql:
   'insert into `file` (`name`, `url`, `vdisk`) values (\'43\', \'20180424_5ade8c7af3684.jpg,ref/2020-04-29/FILE00000000015J.jpg\', \'431\')' }
[2020-04-29T14:24:51.548] [ERROR] app - 401
[2020-04-29T14:24:59.119] [INFO] app - INCORRECT_PASSWORD:
[2020-04-29T14:24:59.121] [ERROR] app - 密码错误
[2020-04-29T14:29:03.813] [ERROR] app - 401
[2020-04-29T14:29:03.815] [ERROR] app - 401
[2020-04-29T14:29:16.724] [ERROR] app - 403
[2020-04-29T14:29:59.824] [ERROR] app - 401
[2020-04-29T14:29:59.826] [ERROR] app - 401
[2020-04-29T14:34:16.940] [ERROR] app - 401
[2020-04-29T14:47:06.937] [ERROR] app - 401
[2020-04-29T14:47:06.944] [ERROR] app - 403
[2020-04-29T14:49:24.058] [ERROR] app - 401
[2020-04-29T16:04:29.998] [ERROR] app - 401
[2020-04-29T16:04:43.441] [ERROR] app - Request without token
[2020-04-29T16:04:43.442] [ERROR] app - 没有访问权限
[2020-04-29T16:37:04.302] [ERROR] app - Request without token
[2020-04-29T16:37:04.311] [ERROR] app - 没有访问权限
[2020-04-29T16:37:26.971] [ERROR] app - 401
