[2020-11-16T00:07:13.061] [ERROR] app - 用户名不存在
[2020-11-16T00:07:13.110] [ERROR] app - 用户名不存在
[2020-11-16T00:17:53.585] [ERROR] app - API接口不存在
[2020-11-16T00:17:53.591] [ERROR] app - API接口不存在
[2020-11-16T00:17:53.599] [ERROR] app - API接口不存在
[2020-11-16T00:17:53.603] [ERROR] app - API接口不存在
[2020-11-16T00:19:52.857] [ERROR] app - 用户名不存在
[2020-11-16T00:19:52.894] [ERROR] app - 用户名不存在
[2020-11-16T00:19:56.324] [ERROR] app - API接口不存在
[2020-11-16T00:19:56.331] [ERROR] app - API接口不存在
[2020-11-16T00:19:56.334] [ERROR] app - API接口不存在
[2020-11-16T00:19:56.338] [ERROR] app - API接口不存在
[2020-11-16T00:20:00.549] [ERROR] app - 数据传输错误,请联系管理员
[2020-11-16T00:20:14.577] [ERROR] app - 数据传输错误,请联系管理员
[2020-11-16T00:21:40.817] [ERROR] app - 数据传输错误,请联系管理员
[2020-11-16T00:22:13.716] [ERROR] app - 数据传输错误,请联系管理员
[2020-11-16T00:23:23.635] [ERROR] app - Error: ER_DATA_TOO_LONG: Data too long for column 'user_id' at row 1
    at Query.Sequence._packetToError (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
    at Protocol._enqueue (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:198:25)
    at C:\Users\racky\Desktop\project\hstigger-server\node_modules\_knex@0.13.0@knex\lib\dialects\mysql\index.js:152:18
    at Promise._execute (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:384:9)
    at Promise._resolveFromExecutor (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:518:18)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:482:19)
    at Promise._then (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:261:17)
    at Promise._passThrough (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:94:17)
    at Promise.lastly.Promise.finally (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:103:17)
    at Function.Promise.using (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\using.js:192:37)
    at Runner.run (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_knex@0.13.0@knex\lib\runner.js:51:31)
    at Builder.Target.then (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_knex@0.13.0@knex\lib\interface.js:35:43) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlMessage: "Data too long for column 'user_id' at row 1",
  sqlState: '22001',
  index: 0,
  sql: "insert into `user_setting` (`key`, `user_id`, `value`) values ('accelerates', '5e4b14c0-275e-11eb-80cc-ffaaa6d04ce0', '')"
}
[2020-11-16T00:39:51.111] [ERROR] app - Error: ER_DATA_TOO_LONG: Data too long for column 'user_id' at row 1
    at Query.Sequence._packetToError (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
    at Protocol._enqueue (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:198:25)
    at C:\Users\racky\Desktop\project\hstigger-server\node_modules\_knex@0.13.0@knex\lib\dialects\mysql\index.js:152:18
    at Promise._execute (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:384:9)
    at Promise._resolveFromExecutor (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:518:18)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:482:19)
    at Promise._then (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:261:17)
    at Promise._passThrough (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:94:17)
    at Promise.lastly.Promise.finally (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:103:17)
    at Function.Promise.using (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\using.js:192:37)
    at Runner.run (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_knex@0.13.0@knex\lib\runner.js:51:31)
    at Builder.Target.then (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_knex@0.13.0@knex\lib\interface.js:35:43) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlMessage: "Data too long for column 'user_id' at row 1",
  sqlState: '22001',
  index: 0,
  sql: "insert into `user_setting` (`key`, `user_id`, `value`) values ('accelerates', '5e4b14c0-275e-11eb-80cc-ffaaa6d04ce0', '')"
}
[2020-11-16T00:40:23.173] [ERROR] app - 用户名不存在
[2020-11-16T00:40:23.175] [ERROR] app - 用户名不存在
[2020-11-16T00:40:33.475] [ERROR] app - API接口不存在
[2020-11-16T00:40:33.528] [ERROR] app - API接口不存在
[2020-11-16T00:40:33.528] [ERROR] app - API接口不存在
[2020-11-16T00:40:33.546] [ERROR] app - API接口不存在
[2020-11-16T00:42:32.319] [ERROR] app - API接口不存在
[2020-11-16T00:42:32.354] [ERROR] app - API接口不存在
[2020-11-16T00:42:32.378] [ERROR] app - API接口不存在
[2020-11-16T00:42:32.379] [ERROR] app - API接口不存在
[2020-11-16T00:45:07.414] [ERROR] app - API接口不存在
[2020-11-16T00:45:07.499] [ERROR] app - API接口不存在
[2020-11-16T00:45:07.504] [ERROR] app - API接口不存在
[2020-11-16T00:45:07.509] [ERROR] app - API接口不存在
[2020-11-16T01:23:44.025] [ERROR] app - 用户名不存在
[2020-11-16T01:23:44.027] [ERROR] app - 用户名不存在
[2020-11-16T01:23:46.824] [ERROR] app - ReferenceError: Setting is not defined
    at Object.o.getUserInfo (C:\Users\racky\Desktop\project\hstigger-server\models\Account.js:127:25)
    at async Object.o.login (C:\Users\racky\Desktop\project\hstigger-server\models\Account.js:109:18)
    at async Object.o.createSessionByLogin (C:\Users\racky\Desktop\project\hstigger-server\models\Session.js:60:18)
    at async Object.out.Post (C:\Users\racky\Desktop\project\hstigger-server\controllers\sessions.js:13:19)
    at async RestfulAPIMethods.<computed> (C:\Users\racky\Desktop\project\hstigger-server\middlewares\router.js:27:26)
    at async C:\Users\racky\Desktop\project\hstigger-server\middlewares\router.js:74:7
    at async module.exports (C:\Users\racky\Desktop\project\hstigger-server\middlewares\auth.js:32:7)
    at async module.exports (C:\Users\racky\Desktop\project\hstigger-server\middlewares\response.js:8:9)
    at async cors (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa2-cors@2.0.6@koa2-cors\dist\index.js:91:9)
    at async C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa-log4@2.3.2@koa-log4\koa-logger.js:86:7
[2020-11-16T01:27:04.150] [ERROR] app - 用户名不存在
[2020-11-16T01:27:04.154] [ERROR] app - 用户名不存在
[2020-11-16T01:27:08.161] [ERROR] app - API接口不存在
[2020-11-16T01:27:08.229] [ERROR] app - API接口不存在
[2020-11-16T01:27:08.237] [ERROR] app - API接口不存在
[2020-11-16T01:27:08.238] [ERROR] app - API接口不存在
[2020-11-16T01:28:09.237] [ERROR] app - 用户名不存在
[2020-11-16T01:28:09.241] [ERROR] app - 用户名不存在
[2020-11-16T01:28:13.712] [ERROR] app - API接口不存在
[2020-11-16T01:28:13.734] [ERROR] app - API接口不存在
[2020-11-16T01:28:13.774] [ERROR] app - API接口不存在
[2020-11-16T01:28:13.797] [ERROR] app - API接口不存在
[2020-11-16T01:28:41.525] [ERROR] app - API接口不存在
[2020-11-16T01:28:41.562] [ERROR] app - API接口不存在
[2020-11-16T01:28:41.568] [ERROR] app - API接口不存在
[2020-11-16T01:28:41.591] [ERROR] app - API接口不存在
[2020-11-16T01:38:31.067] [ERROR] app - API接口不存在
[2020-11-16T01:38:31.146] [ERROR] app - API接口不存在
[2020-11-16T01:38:31.147] [ERROR] app - API接口不存在
[2020-11-16T01:38:31.147] [ERROR] app - API接口不存在
[2020-11-16T01:38:33.614] [ERROR] app - ReferenceError: id is not defined
    at Object.o.set (C:\Users\racky\Desktop\project\hstigger-server\models\Setting.js:92:44)
    at async Object.out.Patch (C:\Users\racky\Desktop\project\hstigger-server\controllers\settings.js:26:3)
    at async RestfulAPIMethods.<computed> (C:\Users\racky\Desktop\project\hstigger-server\middlewares\router.js:27:26)
    at async module.exports (C:\Users\racky\Desktop\project\hstigger-server\middlewares\authRouter.js:13:4)
    at async C:\Users\racky\Desktop\project\hstigger-server\middlewares\router.js:74:7
    at async module.exports (C:\Users\racky\Desktop\project\hstigger-server\middlewares\auth.js:38:3)
    at async module.exports (C:\Users\racky\Desktop\project\hstigger-server\middlewares\response.js:8:9)
    at async cors (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa2-cors@2.0.6@koa2-cors\dist\index.js:91:9)
    at async C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa-log4@2.3.2@koa-log4\koa-logger.js:86:7
[2020-11-16T01:45:03.239] [ERROR] app - 用户名不存在
[2020-11-16T01:45:03.268] [ERROR] app - 用户名不存在
[2020-11-16T01:45:08.882] [ERROR] app - API接口不存在
[2020-11-16T01:45:08.910] [ERROR] app - API接口不存在
[2020-11-16T01:45:08.910] [ERROR] app - API接口不存在
[2020-11-16T01:45:08.913] [ERROR] app - API接口不存在
[2020-11-16T01:51:32.681] [ERROR] app - 用户名不存在
[2020-11-16T01:51:32.683] [ERROR] app - 用户名不存在
[2020-11-16T01:52:01.840] [ERROR] app - API接口不存在
[2020-11-16T01:52:01.865] [ERROR] app - API接口不存在
[2020-11-16T01:52:01.891] [ERROR] app - API接口不存在
[2020-11-16T01:52:01.917] [ERROR] app - API接口不存在
[2020-11-16T01:52:17.540] [ERROR] app - API接口不存在
[2020-11-16T01:52:17.589] [ERROR] app - API接口不存在
[2020-11-16T01:52:17.600] [ERROR] app - API接口不存在
[2020-11-16T01:52:17.601] [ERROR] app - API接口不存在
[2020-11-16T02:24:13.786] [ERROR] app - 用户名不存在
[2020-11-16T02:24:13.788] [ERROR] app - 用户名不存在
[2020-11-16T02:24:54.928] [ERROR] app - 用户名不存在
[2020-11-16T02:24:54.934] [ERROR] app - 用户名不存在
[2020-11-16T02:25:24.068] [ERROR] app - 用户名不存在
[2020-11-16T02:26:06.482] [ERROR] app - TypeError: o.getActions is not a function
    at Object.o.getUserInfo (C:\Users\racky\Desktop\project\hstigger-server\models\Account.js:152:31)
    at async Object.o.login (C:\Users\racky\Desktop\project\hstigger-server\models\Account.js:132:18)
    at async Object.o.createSessionByLogin (C:\Users\racky\Desktop\project\hstigger-server\models\Session.js:60:18)
    at async Object.out.Post (C:\Users\racky\Desktop\project\hstigger-server\controllers\sessions.js:13:19)
    at async RestfulAPIMethods.<computed> (C:\Users\racky\Desktop\project\hstigger-server\middlewares\router.js:27:26)
    at async C:\Users\racky\Desktop\project\hstigger-server\middlewares\router.js:74:7
    at async module.exports (C:\Users\racky\Desktop\project\hstigger-server\middlewares\auth.js:30:7)
    at async module.exports (C:\Users\racky\Desktop\project\hstigger-server\middlewares\response.js:8:9)
    at async cors (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa2-cors@2.0.6@koa2-cors\dist\index.js:91:9)
    at async C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa-log4@2.3.2@koa-log4\koa-logger.js:86:7
[2020-11-16T02:27:17.524] [ERROR] app - API接口不存在
[2020-11-16T02:27:17.539] [ERROR] app - API接口不存在
[2020-11-16T02:27:17.548] [ERROR] app - API接口不存在
[2020-11-16T02:27:17.579] [ERROR] app - API接口不存在
[2020-11-16T02:28:26.389] [ERROR] app - TypeError: Account.setMenu is not a function
    at Object.out.AddRelated (C:\Users\racky\Desktop\project\hstigger-server\controllers\users.js:13:19)
    at RestfulAPIMethods.<computed> (C:\Users\racky\Desktop\project\hstigger-server\middlewares\router.js:27:52)
    at dispatch (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at module.exports (C:\Users\racky\Desktop\project\hstigger-server\middlewares\authRouter.js:13:10)
    at dispatch (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\racky\Desktop\project\hstigger-server\middlewares\router.js:74:13
    at dispatch (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\racky\Desktop\project\hstigger-server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
[2020-11-16T02:29:21.582] [ERROR] app - 用户名不存在
[2020-11-16T02:29:21.600] [ERROR] app - 用户名不存在
[2020-11-16T02:31:27.458] [ERROR] app - 用户名不存在
[2020-11-16T02:31:27.460] [ERROR] app - 用户名不存在
[2020-11-16T02:31:54.741] [ERROR] app - API接口不存在
[2020-11-16T02:31:54.764] [ERROR] app - API接口不存在
[2020-11-16T02:31:54.767] [ERROR] app - API接口不存在
[2020-11-16T02:31:54.787] [ERROR] app - API接口不存在
[2020-11-16T02:32:20.798] [ERROR] app - 用户名不存在
[2020-11-16T02:32:20.801] [ERROR] app - 用户名不存在
[2020-11-16T02:32:27.055] [ERROR] app - API接口不存在
[2020-11-16T02:32:27.062] [ERROR] app - API接口不存在
[2020-11-16T02:32:27.065] [ERROR] app - API接口不存在
[2020-11-16T02:32:27.065] [ERROR] app - API接口不存在
[2020-11-16T02:33:10.204] [ERROR] app - API接口不存在
[2020-11-16T02:33:10.211] [ERROR] app - API接口不存在
[2020-11-16T02:33:10.215] [ERROR] app - API接口不存在
[2020-11-16T02:33:10.217] [ERROR] app - API接口不存在
[2020-11-16T02:34:00.478] [ERROR] app - API接口不存在
[2020-11-16T02:34:00.485] [ERROR] app - API接口不存在
[2020-11-16T02:34:00.489] [ERROR] app - API接口不存在
[2020-11-16T02:34:00.490] [ERROR] app - API接口不存在
[2020-11-16T02:36:03.228] [ERROR] app - API接口不存在
[2020-11-16T02:36:03.233] [ERROR] app - API接口不存在
[2020-11-16T02:36:03.240] [ERROR] app - API接口不存在
[2020-11-16T02:36:03.242] [ERROR] app - API接口不存在
[2020-11-16T02:37:57.994] [ERROR] app - API接口不存在
[2020-11-16T02:37:58.001] [ERROR] app - API接口不存在
[2020-11-16T02:37:58.005] [ERROR] app - API接口不存在
[2020-11-16T02:37:58.006] [ERROR] app - API接口不存在
[2020-11-16T02:40:27.348] [ERROR] app - API接口不存在
[2020-11-16T02:40:27.357] [ERROR] app - API接口不存在
[2020-11-16T02:40:27.360] [ERROR] app - API接口不存在
[2020-11-16T02:40:27.361] [ERROR] app - API接口不存在
[2020-11-16T02:41:26.454] [ERROR] app - API接口不存在
[2020-11-16T02:41:26.461] [ERROR] app - API接口不存在
[2020-11-16T02:41:26.465] [ERROR] app - API接口不存在
[2020-11-16T02:41:26.466] [ERROR] app - API接口不存在
[2020-11-16T02:41:30.573] [ERROR] app - API接口不存在
[2020-11-16T02:41:30.581] [ERROR] app - API接口不存在
[2020-11-16T02:41:30.584] [ERROR] app - API接口不存在
[2020-11-16T02:41:30.585] [ERROR] app - API接口不存在
[2020-11-16T02:43:20.418] [ERROR] app - API接口不存在
[2020-11-16T02:43:20.424] [ERROR] app - API接口不存在
[2020-11-16T02:43:20.429] [ERROR] app - API接口不存在
[2020-11-16T02:43:20.432] [ERROR] app - API接口不存在
[2020-11-16T02:43:51.012] [ERROR] app - API接口不存在
[2020-11-16T02:43:56.758] [ERROR] app - API接口不存在
[2020-11-16T02:43:56.759] [ERROR] app - API接口不存在
[2020-11-16T02:43:56.761] [ERROR] app - API接口不存在
[2020-11-16T02:43:56.770] [ERROR] app - API接口不存在
